### ISSUE TITLE
How can I change the width of the timestamp column?

### ISSUE THREAD

**Issue by dixonge** [kookma/TW-Todolist#13] opened 2022-05-25 12:14 UTC
There are five possible characters in this column. Two numbers, a colon, and two more numbers.

The last number always wraps to a second line, even in your demo TW!

Would like this to not wrap. Thanks.

**Comment by kookma** [comment] 2022-05-26 20:19
It wrap if it has not enough width see:

![image](https://user-images.githubusercontent.com/830394/170573163-1e42b21a-56fa-44fd-8aa6-ff7964d7680f.png)

So do you use it with enough space?

**Comment by kookma** [comment] 2022-05-26 20:21
By the way the selector here is   

`kk-todolist-date`

customize its width as you like!

**Comment by dixonge** [comment] 2022-05-27 11:53
My apologies! I am referring to the journal entries using ```<<interstitial-ui caption:"" width:"" base:"">>```

That is where the problem occurs. Here is how it looks on your demo page:

<img width="497" alt="interstitial-ui-macro-column-width" src="https://user-images.githubusercontent.com/1578506/170694321-423a614e-4445-4e87-a1cc-74648cc3a747.png">

**Comment by kookma** [comment] 2022-05-28 02:40
Strangely I cannot reproduce this on demo page!
but the css class is `kk-todolist-done` you can set your desired width!

**Comment by dixonge** [comment] 2022-05-28 03:08
I got that screenshot from your site:

https://kookma.github.io/TW-Todolist/

Go to the ToDo-List Tutorial tiddler, click the Interstitial-UI Macro tab. The width of the timestamp column is being set by a Style statement, overriding anything in the CSS file. I'm not sure what tiddler generates the html there, but that's where it needs to change. 3.2em is wide enough, or 42 pixels.

I tested your site on both Chrome and Safari.

**Comment by kookma** [comment] 2022-05-28 18:23
the css class is kk-todolist-done you can set your desired width!
Still I cannot reproduce it not on Chrome, Edge, nor in FireFox.

**Comment by dixonge** [comment] 2022-05-28 20:01
I also just reproduced it in Firefox. Here is how you can see the problem on your own web site:

1. Go to this URL: https://kookma.github.io/TW-Todolist/
2. Scroll down to the Todolist Tutorial tiddler
3. Click on the 'Interstitial-UI macro' tab on the left.
4. Scroll down to the 'Example' section
There you can plainly see the timestamp column wraps on every time entry.

Optionally you can go to the tiddler titled '18th November 2021' and see the same wrapping.

I also downloaded your Mehregan tiddlywiki - if I open the example journal entry '2021-11-19 Friday' the same wrapping occurs.

I have now reproduced this in three browsers on my laptop and two browsers on my iPhone. On my laptop I also tested this on my own personal TiddlyWiki.

I have tried changing the width using the kk-todolist-done class, but it only changes one row and the change is lost the next time I refresh.

**Comment by dixonge** [comment] 2022-05-30 02:57
I figured out how to fix this issue.

1. Edit the file ```interstitial-utility.tid``` in the macros folder. In this file, the column width is set by an inline style, which overrides anything in the CSS file (unless you use ```!important```
2. Change the 'style' code from 2.6em to 3.2em
``` <div class="kk-todolist-done" style="width:2.6em"> ```
3. Change this in two different places in this file

After that, the timestamp column is wide enough and the lines don't wrap.

**Comment by kookma** [comment] 2022-06-01 03:09
Thank you! I will remove the inline style here in the next release!

**Comment by applemcg** [comment] 2022-12-09 16:03
I see an update: 1.4.1 and have downloaded; it's working just fine

**Comment by kookma** [comment] 2022-12-09 19:29
This issue has been addressed in Todolist 1.4.1

**Closed by kookma** 2022-12-09 19:29 UTC
Labels: enhancement
